# Generated by Django 6.0.7 on 2026-07-11 17:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_peluqueria', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='atendente',
            options={'verbose_name': 'Atendente', 'verbose_name_plural': 'Atendentes'},
        ),
        migrations.AlterModelOptions(
            name='cliente',
            options={'verbose_name': 'Cliente', 'verbose_name_plural': 'Clientes'},
        ),
        migrations.AlterModelOptions(
            name='factura',
            options={'verbose_name': 'Factura', 'verbose_name_plural': 'Facturas'},
        ),
        migrations.AlterModelOptions(
            name='gasto',
            options={'verbose_name': 'Gasto', 'verbose_name_plural': 'Gastos'},
        ),
        migrations.AlterModelOptions(
            name='historialreserva',
            options={'verbose_name': 'Historial de Reserva', 'verbose_name_plural': 'Historial de Reservas'},
        ),
        migrations.AlterModelOptions(
            name='ingreso',
            options={'verbose_name': 'Ingreso', 'verbose_name_plural': 'Ingresos'},
        ),
        migrations.AlterModelOptions(
            name='lineafactura',
            options={'verbose_name': 'Línea de Factura', 'verbose_name_plural': 'Líneas de Factura'},
        ),
        migrations.AlterModelOptions(
            name='producto',
            options={'verbose_name': 'Producto', 'verbose_name_plural': 'Productos'},
        ),
        migrations.AlterModelOptions(
            name='promocion',
            options={'verbose_name': 'Promoción', 'verbose_name_plural': 'Promociones'},
        ),
        migrations.AlterModelOptions(
            name='proveedor',
            options={'verbose_name': 'Proveedor', 'verbose_name_plural': 'Proveedores'},
        ),
        migrations.AlterModelOptions(
            name='reserva',
            options={'verbose_name': 'Reserva', 'verbose_name_plural': 'Reservas'},
        ),
        migrations.AlterModelOptions(
            name='stock',
            options={'verbose_name': 'Stock', 'verbose_name_plural': 'Stocks'},
        ),
        migrations.AlterField(
            model_name='factura',
            name='cliente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='facturas', to='gestion_peluqueria.cliente'),
        ),
        migrations.AlterField(
            model_name='historialreserva',
            name='reserva',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historial', to='gestion_peluqueria.reserva'),
        ),
        migrations.AlterField(
            model_name='reserva',
            name='cliente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservas', to='gestion_peluqueria.cliente'),
        ),
        migrations.AlterField(
            model_name='reserva',
            name='estado',
            field=models.CharField(choices=[('pendiente', 'Pendiente'), ('realizada', 'Realizada'), ('cancelada', 'Cancelada'), ('finalizada', 'Finalizada')], default='pendiente', max_length=50),
        ),
        migrations.AlterField(
            model_name='reserva',
            name='observaciones',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='stock',
            name='producto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stocks', to='gestion_peluqueria.producto'),
        ),
    ]
