# Generated by Django 4.2 on 2026-03-24 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Promocion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('descuento', models.DecimalField(decimal_places=2, max_digits=10)),
                ('tipo_descuento', models.CharField(choices=[('porcentaje', 'Porcentaje'), ('fijo', 'Fijo')], max_length=50)),
                ('vigencia', models.DateField()),
            ],
        ),
    ]
