# Generated by Django 4.2 on 2026-03-25 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facturacion', '0002_alter_gasto_fecha_alter_ingreso_fecha'),
    ]

    operations = [
        migrations.AddField(
            model_name='gasto',
            name='categoria',
            field=models.CharField(default='Varios', max_length=100),
        ),
        migrations.AddField(
            model_name='gasto',
            name='iva_incluido',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='gasto',
            name='iva_porcentaje',
            field=models.DecimalField(decimal_places=2, default=21.0, max_digits=5),
        ),
        migrations.AddField(
            model_name='gasto',
            name='subcategoria',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='ingreso',
            name='categoria',
            field=models.CharField(default='Otros', max_length=100),
        ),
        migrations.AddField(
            model_name='ingreso',
            name='iva_incluido',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='ingreso',
            name='iva_porcentaje',
            field=models.DecimalField(decimal_places=2, default=21.0, max_digits=5),
        ),
        migrations.AddField(
            model_name='ingreso',
            name='subcategoria',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
