# Generated by Django 4.2 on 2026-03-24 18:25

from decimal import Decimal
from django.db import migrations, models
import django.db.models.deletion
import personal.models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0002_servicio'),
        ('reservas', '0002_reserva_actualizado_en_reserva_cancelado_en_and_more'),
        ('personal', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Aviso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('mensaje', models.TextField()),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AddField(
            model_name='atendente',
            name='comision_fija',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10),
        ),
        migrations.AddField(
            model_name='atendente',
            name='comision_porcentaje',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=5),
        ),
        migrations.AddField(
            model_name='atendente',
            name='dias_laborales',
            field=models.JSONField(blank=True, default=personal.models.default_work_days),
        ),
        migrations.AddField(
            model_name='atendente',
            name='hora_fin',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='atendente',
            name='hora_inicio',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='atendente',
            name='servicios',
            field=models.ManyToManyField(blank=True, related_name='atendentes', to='inventario.servicio'),
        ),
        migrations.CreateModel(
            name='NominaMensual',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.PositiveIntegerField()),
                ('month', models.PositiveIntegerField()),
                ('salario_base', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('comision_fija_total', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('comision_porcentaje_total', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('otros', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('total', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('atendente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='nominas', to='personal.atendente')),
            ],
            options={
                'ordering': ['-year', '-month', 'atendente__apellido'],
                'unique_together': {('atendente', 'year', 'month')},
            },
        ),
        migrations.CreateModel(
            name='NominaItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('concepto', models.CharField(max_length=200)),
                ('importe', models.DecimalField(decimal_places=2, max_digits=10)),
                ('nomina', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='personal.nominamensual')),
                ('reserva', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='reservas.reserva')),
            ],
        ),
        migrations.CreateModel(
            name='AvisoDestinatario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('leido', models.BooleanField(default=False)),
                ('leido_en', models.DateTimeField(blank=True, null=True)),
                ('atendente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='avisos', to='personal.atendente')),
                ('aviso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='destinatarios', to='personal.aviso')),
            ],
            options={
                'unique_together': {('aviso', 'atendente')},
            },
        ),
    ]
