# Generated by Django 4.2 on 2026-03-25 10:22

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personal', '0002_aviso_atendente_comision_fija_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='nominamensual',
            name='deducciones',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10),
        ),
        migrations.AddField(
            model_name='nominamensual',
            name='estado',
            field=models.CharField(choices=[('pendiente', 'Pendiente'), ('pagada', 'Pagada')], default='pendiente', max_length=20),
        ),
        migrations.AddField(
            model_name='nominamensual',
            name='fecha_pago',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='nominamensual',
            name='retencion_irpf',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10),
        ),
        migrations.AddField(
            model_name='nominamensual',
            name='seguridad_social',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10),
        ),
        migrations.AddField(
            model_name='nominamensual',
            name='total_neto',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10),
        ),
    ]
