# Generated by Django 4.2 on 2026-03-24 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='gasto_acumulado',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='cliente',
            name='preferencias',
            field=models.TextField(blank=True),
        ),
    ]
