# Generated by Django 4.2 on 2026-03-24 11:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('personal', '0001_initial'),
        ('reservas', '0002_reserva_actualizado_en_reserva_cancelado_en_and_more'),
        ('inventario', '0002_servicio'),
        ('clientes', '0002_cliente_gasto_acumulado_cliente_preferencias'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClienteServicio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('hora', models.TimeField()),
                ('precio', models.DecimalField(decimal_places=2, max_digits=10)),
                ('atendente', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='personal.atendente')),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historial_servicios', to='clientes.cliente')),
                ('reserva', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='reservas.reserva')),
                ('servicio', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='inventario.servicio')),
            ],
            options={
                'verbose_name_plural': 'Historial de Servicios',
                'ordering': ['-fecha', '-hora'],
            },
        ),
    ]
